Update README.md
Dun-sin/HearItFresh pull request #3
Opened 2023-02-14 11:51 UTC by mithindev

closes #2 

Update README.md file with clearer project description, detailed instructions, and a table of contents to make it easier for users to understand and contribute to the project.

2023-02-14 11:56 UTC, Dun-sin commented
Calm down my friend😭 didn't even assign you to anything.

2023-02-14 12:04 UTC, Dun-sin commented
But thanks anyway

2023-02-14 12:05 UTC, mithindev commented
I am sorry, But thanks.

2023-02-14 13:13 UTC, Dun-sin requested changes
70% of this PR is just wrong, if you still want to work on this properly let me know, otherwise i will close this

2023-02-14 13:13 UTC, Dun-sin commented on README.md
> +To use HearItFresh, simply navigate to the website and sign up for an account. Once logged in, you can search for songs, listen to them, and add them to playlists. You can also follow other users and
This isn't what my project does

2023-02-14 13:13 UTC, Dun-sin commented on README.md
> +4. Set up the database by running `npm run db:setup`.
there's no database

2023-02-14 13:13 UTC, Dun-sin commented on README.md
> +Note: You will need to have Node.js and MongoDB installed on your machine to run this application.
there's no backend either

2023-02-14 13:13 UTC, Dun-sin commented on README.md
> +- Follow other users to see their music recommendations
This isn't what my app does, did you use chatGPT to generate this readme lol

2023-02-14 13:13 UTC, Dun-sin commented on README.md
> +HearItFresh is a web application that allows users to discover and share new music. Users can sign up for an account, search for and listen to songs, create and share playlists, and follow other user
Once again, try to actually be genuine, rather than using ChatGPT to do this

2023-02-14 13:20 UTC, mithindev commented
Ok! I really want to work on this. Can you assign me this task?

2023-02-14 13:28 UTC, Dun-sin commented
> Ok! I really want to work on this. Can you assign me this task?

I will assign you officially, Hopefully you see the review notes above

2023-02-15 16:24 UTC, mithindev commented
Hello, @Dun-sin. Just want to remind you that I am not idle. I am working on it.

2023-02-15 17:09 UTC, Dun-sin commented
> Hello, @Dun-sin. Just want to remind you that I am not idle. I am working on it.

well thanks for letting me know, i don't think it takes more than an hour tho, what's taking your time?

2023-02-16 01:49 UTC, mithindev reviewed
Viewed for correction.

2023-02-16 02:00 UTC, mithindev commented
Hello @Dun-sin I have made the changes as you've guided. Should I make more changes? 
- Thank you so much for reviewing.

2023-02-16 09:47 UTC, Dun-sin requested changes

2023-02-16 09:47 UTC, Dun-sin commented on README.md
> +<h2 align="center">Explore fresh music inspired by the Spotify playlists you ❤️</h2>
```suggestion
<h2 align="center">Discover new tracks with Hear It Fresh! This user-friendly web app generates personalized Spotify playlists based on your favourite artists or a Spotify playlist link. Explore fresh music.</h2>
```

2023-02-16 09:47 UTC, Dun-sin commented on README.md
> +- Create playlists using artist, track, or playlist seeds as a basis.
```suggestion
- Create new playlists using your favourite artists or an existing playlist
```

2023-02-16 09:47 UTC, Dun-sin commented on README.md
> +- Use a personal playlist as a basis to generate new playlists.
```suggestion
```

2023-02-16 09:47 UTC, Dun-sin commented on README.md
> +- Tune parameters like different genre, none popular artists etc. to further customize the playlist
```suggestion
- Get better results by changing the parameters to either getting a playlist of different artists opposite to your taste or get less popular artists
```

2023-02-16 09:52 UTC, Dun-sin commented
@mithindev it's much better, thanks for fixing them, just a little more change to Your PR, i gave the new review above

2023-02-16 09:55 UTC, Dun-sin approved these changes

2023-02-16 09:57 UTC, merged

2023-02-16 09:57 UTC, Dun-sin commented
Thanks for this @mithindev

2023-02-16 10:02 UTC, mithindev commented
Sure.  I will do it.